# Generated by Django 5.0.3 on 2024-04-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_networking_app", "0001_initial"),
    ]

    operations = []
