# Generated by Django 5.0.3 on 2024-03-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_networking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
